// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wswPt0Kggj-ApOc7SSdKKiEcRT6ga7c',
    appId: '1:180739106401:web:d1b084a71323faf451ec20',
    messagingSenderId: '180739106401',
    projectId: 'todoapp-26e20',
    authDomain: 'todoapp-26e20.firebaseapp.com',
    storageBucket: 'todoapp-26e20.firebasestorage.app',
    measurementId: 'G-E23580MQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSm80io-VGaquXAlJ3reKYUjqoOADN2Q',
    appId: '1:180739106401:android:80fc2fcdd20b185651ec20',
    messagingSenderId: '180739106401',
    projectId: 'todoapp-26e20',
    storageBucket: 'todoapp-26e20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7BxHMbnYThWTnyiIE8wpy_uVqcxXYk4M',
    appId: '1:180739106401:ios:8c5b663ff0a1e2b151ec20',
    messagingSenderId: '180739106401',
    projectId: 'todoapp-26e20',
    storageBucket: 'todoapp-26e20.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );
}
